### ISSUE TITLE
Partial refresh

### ISSUE THREAD

**Issue by a1ex4nd3r** [djaffry/oeffis-paper#2]
Hi,

is there a possibility to refresh the screen partially (fast) without waiting? Currently the screen refreshes on every update slowly.

Regards

**Comment by djaffry** [comment]
Hi Alexander,

unfortunately no. It's not possible due to the e-ink display hardware not supporting this feature. Have a look at the _Selection Guide_ section down below: [Waveshare E-Ink display](https://www.waveshare.com/7.5inch-e-paper-hat-b.htm#Selection%20Guide). _7.5inch e-Paper HAT (B)_ is the display I'm currently using.

This issue bugs me too.. I'm currently looking out for some other display to mitigate this.. 

Greetings!
