### ISSUE TITLE
After setup.sh -> nohup package not installed (no find) - Raspian Buster

### ISSUE THREAD

**Issue by njordan77** [djaffry/oeffis-paper#3]
Any clue why the setup.sh already brings up error logs on nohup Installation?

E: Unable to locate package nohup
Some error occured. Exiting...

Do not know nohup so cannot tell how important it will be for the overall system to work...

**Comment by njordan77** [comment]
or is there any mistake in the script and you mean the nohup extension to not show anything on the screen?

**Comment by njordan77** [comment]
upps - next issue. did everything according to your step-by-step intro on a Raspi 3A+ with Raspbian Buster.

after start.sh
 failed to run command 'venv/bin/python3': No such file or directory

**Comment by njordan77** [comment]
hm....should the script really do dependencies by itself. i now started main.py manually and i get the next problem feedback.

pi@InfoScreen:~/oeffis-paper $ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from display.display_driver import UIDriver
  File "/home/pi/oeffis-paper/display/display_driver.py", line 1, in <module>
    from .bpm_render import render, render_exception
  File "/home/pi/oeffis-paper/display/bpm_render.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

Any Clue what here again is the problem. Thanks a lot Norbert

**Comment by djaffry** [comment]
Hi Norbert,

> Do not know nohup so cannot tell how important it will be for the overall system to work...

[nohup](https://manpages.ubuntu.com/manpages/trusty/en/man1/nohup.1.html) ("no hang up") could be quite important for your system to run. It's used to spawn a process which won't get terminated if you log out or, more importantly, end your `ssh` connection. So unless you run the code directly from your pi without a `ssh` session, you will probably need it.

> or is there any mistake in the script

Seems like `nohup` got merged into `coreutils` with the raspbian update to debian buster: https://archive.raspbian.org/raspbian/dists/buster/main/binary-armhf/Packages
That's why `apt` throws you the error: 
> E: Unable to locate package nohup

Fixed it in [commit dabb002](https://github.com/djaffry/oeffis-paper/commit/dabb00274f1ec74fc96a9d793cc29468c9b9c847), thanks!



> upps - next issue. did everything according to your step-by-step intro on a Raspi 3A+ with Raspbian Buster.
> 
> after start.sh
> failed to run command 'venv/bin/python3': No such file or directory

That's probably because your `scripts/setup.sh` did not run through successfully.

> failed to run command 'venv/bin/python3': No such file or directory

See, this line tells us that your `venv` [Python Virtual Environment](https://docs.python.org/3/tutorial/venv.html) isn't there. It was probably never initialized because the error above aborts the script. The `venv` installing part  on [line 124](https://github.com/djaffry/oeffis-paper/blob/8725339e6201480596b0122ae0b4413b5d566cf6/scripts/setup.sh#L124) comes after the line where the error occured [line 105](https://github.com/djaffry/oeffis-paper/blob/8725339e6201480596b0122ae0b4413b5d566cf6/scripts/setup.sh#L105).

> hm....should the script really do dependencies by itself

Yes, that's its intended purpose. I know it's not the best script and I wish I could pour more recources in making it perfect but I have only so much time.. But you can always install the dependencies und run the code as you wish.

> i now started main.py manually and i get the next problem feedback.
> 
> pi@InfoScreen:~/oeffis-paper $ sudo python3 main.py
> Traceback (most recent call last):
> File "main.py", line 9, in
> from display.display_driver import UIDriver
> File "/home/pi/oeffis-paper/display/display_driver.py", line 1, in
> from .bpm_render import render, render_exception
> File "/home/pi/oeffis-paper/display/bpm_render.py", line 1, in
> from PIL import Image
> ModuleNotFoundError: No module named 'PIL'

That's because your "standard" python does not have the necessary dependencies and therefore cannot import the packages needed by e.g. `/home/pi/oeffis-paper/display/display_driver.py`. And in our case since the `venv` isn't there, the dependencies are missing as well. You could theoretically install the dependencies system wide, but that's usually not good practice. If you have a few python projects running without creating seperate `venv`s, you might experience some dependency hell. I recommend you to read more about the [Python Virtual Environment](https://docs.python.org/3/tutorial/venv.html) if you are interested.

I would recommend you to `git pull` the latest commit and try running `setup.sh` again.

Btw. if you haven't done already, you need to activate SPI on your raspberry pi too so the pi can communicate to the e-paper screen. It's part of the e-paper setup process. [howto](https://www.raspberrypi.org/documentation/configuration/raspi-config.md)
